import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  reviewSidebar: [
    "index",

    {
      type: "category",
      label: "书评",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "autogenerated",
          dirName: "book",
        },
      ],
    },
  ],
};

export default sidebars;
